### PR TITLE
Add EIP-1559 support

### PR DESCRIPTION
**Pull request by lekhovitsky**
In this PR: 
* Modify `Flashbots.sign_bundle` to work with type 1 and 2 transactions (as described in [EIP-2178](https://eips.ethereum.org/EIPS/eip-2718))
* Implement parsing of signed transactions to correctly handle nonces and more-or-less match the js library [behavior](https://github.com/flashbots/ethers-provider-flashbots-bundle/blob/master/src/index.ts#L334)
* Add minimal working example of post-London flashbots usage
* Bump `web3py` dependency to `5.22` and project version to `1.0.1`
* Some, generally unnecessary, code style refinements

### CODE REVIEW

**Comment by oraclown** [comment]
Hey, thanks for adding this. Getting an error when trying to test using the Georli testnet relay:
```
user:~/web3-flashbots$ poetry run python examples/eip1559.py
Using python3 (3.9.7)
Sender account balance: 6.23970569 ETH
Receiver account balance: 0 ETH
Traceback (most recent call last):
  File "examples/eip1559.py", line 88, in <module>
    main()
  File "examples/eip1559.py", line 71, in main
    results.append(w3.flashbots.send_bundle(bundle, target_block_number=target_block))
  File "/home/user/.cache/pypoetry/virtualenvs/flashbots-hW9zp6-l-py3.9/lib/python3.8/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/home/user/.cache/pypoetry/virtualenvs/flashbots-hW9zp6-l-py3.9/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
    response = self._make_request(method, params)
  File "/home/user/.cache/pypoetry/virtualenvs/flashbots-hW9zp6-l-py3.9/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
    return request_func(method, params)
  File "/home/user/web3-flashbots/flashbots/middleware.py", line 33, in middleware
    return flashbots_provider.make_request(method, params)
  File "/home/user/web3-flashbots/flashbots/provider.py", line 52, in make_request
    raw_response = make_post_request(
  File "/home/user/.cache/pypoetry/virtualenvs/flashbots-hW9zp6-l-py3.9/lib/python3.8/site-packages/web3/_utils/request.py", line 49, in make_post_request
    response.raise_for_status()
  File "/home/user/.cache/pypoetry/virtualenvs/flashbots-hW9zp6-l-py3.9/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://relay-goerli.flashbots.net/
```

**Comment by lekhovitsky** [comment]
Hi, @oraclown! I wasn't able to reproduce the error &mdash; for me the example works on Goerli after changing `PROVIDER` and `FLASHBOTS_HTTP_PROVIDER_URI` to their testnet counterparts, and  `chainId` from 1 to 5.

Could it be something with versions in your environment? (Say, `.../lib/python3.8/...` in the provided traceback)

**Comment by oraclown** [comment]
> Hi, @oraclown! I wasn't able to reproduce the error — for me the example works on Goerli after changing `PROVIDER` and `FLASHBOTS_HTTP_PROVIDER_URI` to their testnet counterparts, and `chainId` from 1 to 5.
> 
> Could it be something with versions in your environment? (Say, `.../lib/python3.8/...` in the provided traceback)

Thanks for the response. Good point about the environment, I'll try to clean it up.

Just to make sure are your env variables like so:
`PROVIDER=https://goerli.infura.io/v3/**********`
`FLASHBOTS_HTTP_PROVIDER_URI=https://relay-goerli.flashbots.net`
?

**Comment by lekhovitsky** [comment]
> Just to make sure are your env variables like so: 
> `PROVIDER=https://goerli.infura.io/v3/**********` 
> `FLASHBOTS_HTTP_PROVIDER_URI=https://relay-goerli.flashbots.net` 
> ?

Yes.

**Comment by oraclown** [comment]
> Hi, @oraclown! I wasn't able to reproduce the error — for me the example works on Goerli after changing `PROVIDER` and `FLASHBOTS_HTTP_PROVIDER_URI` to their testnet counterparts, and `chainId` from 1 to 5.
> 
> Could it be something with versions in your environment? (Say, `.../lib/python3.8/...` in the provided traceback)

You were right about env issues. It's working now. Thanks again for making this PR!

**Review by oraclown — APPROVED** [review]
Nice updates

**Pull request merged**
