### PR TITLE
Update RPC parameters to v0.2

### PR DESCRIPTION
**Pull request by azavalla**

### CODE REVIEW

**Comment by epheph** [comment]
@gakonst or @N0K0 do you have any time to review this pr?

**Comment by gakonst** [comment]
Is v0.2 specified anywhere? I can take a look..

**Comment by N0K0** [comment]
Solves https://github.com/flashbots/web3-flashbots/issues/9
Looks good other than the black formatting issues

**Review by N0K0 — APPROVED** [review]

**Comment by azavalla** [comment]
@gakonst Done!

**Comment by epheph** [comment]
Thank you @N0K0  . @gakonst I'll get you the spec

**Pull request merged**
